# This cronjob is a way to ensure that github wont "put my cron jobs to sleep"
# Runs once a day, checking wether there where 45 days since last commit
# Commits to the repository if so, to ensure that the "no activity for 60 days policy"
# Deactivates my cron jobs :,)

name: Keep alive workflow
on:
  schedule:
    - cron: "0 0 * * *"
permissions:
  actions: write
jobs:
  cronjob-based-github-action:
    name: Cronjob based github action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - step 2
      # - step n, use it as the last step
      - uses: gautamkrishnar/keepalive-workflow@v2 # using the workflow with default settings
